### ISSUE TITLE
Update Instagram widget for new account

### ISSUE THREAD

**Issue by peterjmurray22** [UM-Fencing/UMFC-website#21]
Our old account got banned or something, so we need to set up the IG widget again or try to get the account unbanned

**Comment by ethanmad** [comment]
Update the `instagram` key in `config.toml` with the new handle, then generate a new widget on lightwidget.com and use the api key for the `lightwidget` key. Should just take a couple minutes.

**Comment by horberlan** [comment]
I would like to contribute to this project, I am available to work on the site UI :)
They are reading your documentations,
respectfully, horberlan brito.
